################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C55_SRCS := 
A_SRCS := 
ASM_UPPER_SRCS := 
EXE_SRCS := 
LDS_UPPER_SRCS := 
CPP_SRCS := 
CMD_SRCS := 
O_SRCS := 
ELF_SRCS := 
C??_SRCS := 
C64_SRCS := 
C67_SRCS := 
SA_SRCS := 
S64_SRCS := 
OPT_SRCS := 
CXX_SRCS := 
S67_SRCS := 
S??_SRCS := 
PDE_SRCS := 
SV7A_SRCS := 
K_SRCS := 
CLA_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
OUT_SRCS := 
INO_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S_UPPER_SRCS := 
S43_SRCS := 
LD_SRCS := 
CMD_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
C43_SRCS := 
OBJ_SRCS := 
LDS_SRCS := 
S_SRCS := 
CC_SRCS := 
S62_SRCS := 
C62_SRCS := 
C_SRCS := 
C55_DEPS := 
C_UPPER_DEPS := 
S67_DEPS := 
S62_DEPS := 
S_DEPS := 
OPT_DEPS := 
C??_DEPS := 
ASM_UPPER_DEPS := 
S??_DEPS := 
C64_DEPS := 
CXX_DEPS := 
S64_DEPS := 
INO_DEPS := 
CLA_DEPS := 
S55_DEPS := 
SV7A_DEPS := 
EXE_OUTPUTS := 
C62_DEPS := 
C67_DEPS := 
PDE_DEPS := 
K_DEPS := 
C_DEPS := 
CC_DEPS := 
BIN_OUTPUTS := 
C++_DEPS := 
C43_DEPS := 
S43_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 
SA_DEPS := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
SV7A_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
OBJS__QUOTED := 
C67_DEPS__QUOTED := 
K_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
INO_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CPP_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C64_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
S_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S64_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
PDE_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
drivers/display \
drivers \
middlewares/FreeRTOS/Source \
middlewares/FreeRTOS/Source/portable/CCS/ARM_CM4F \
middlewares/FreeRTOS/Source/portable/MemMang \
middlewares/FreeRTOS-Plus-CLI \
middlewares/FreeRTOS-Plus-TCP/source \
middlewares/FreeRTOS-Plus-TCP/source/portable/BufferManagement \
middlewares/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/Common \
middlewares/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/TM4C \
middlewares/lvgl/src/core \
middlewares/lvgl/src/draw/arm2d \
middlewares/lvgl/src/draw \
middlewares/lvgl/src/draw/nxp \
middlewares/lvgl/src/draw/nxp/pxp \
middlewares/lvgl/src/draw/nxp/vglite \
middlewares/lvgl/src/draw/sdl \
middlewares/lvgl/src/draw/stm32_dma2d \
middlewares/lvgl/src/draw/sw \
middlewares/lvgl/src/draw/swm341_dma2d \
middlewares/lvgl/src/font \
middlewares/lvgl/src/hal \
middlewares/lvgl/src/layouts/flex \
middlewares/lvgl/src/layouts/grid \
middlewares/lvgl/src/libs/bmp \
middlewares/lvgl/src/libs/ffmpeg \
middlewares/lvgl/src/libs/freetype \
middlewares/lvgl/src/libs/fsdrv \
middlewares/lvgl/src/libs/gif \
middlewares/lvgl/src/libs/png \
middlewares/lvgl/src/libs/qrcode \
middlewares/lvgl/src/libs/rlottie \
middlewares/lvgl/src/libs/sjpg \
middlewares/lvgl/src/misc \
middlewares/lvgl/src/others/file_explorer \
middlewares/lvgl/src/others/fragment \
middlewares/lvgl/src/others/gridnav \
middlewares/lvgl/src/others/ime \
middlewares/lvgl/src/others/imgfont \
middlewares/lvgl/src/others/monkey \
middlewares/lvgl/src/others/msg \
middlewares/lvgl/src/others/snapshot \
middlewares/lvgl/src/themes/basic \
middlewares/lvgl/src/themes/default \
middlewares/lvgl/src/themes/mono \
middlewares/lvgl/src/widgets/animimg \
middlewares/lvgl/src/widgets/arc \
middlewares/lvgl/src/widgets/bar \
middlewares/lvgl/src/widgets/btn \
middlewares/lvgl/src/widgets/btnmatrix \
middlewares/lvgl/src/widgets/calendar \
middlewares/lvgl/src/widgets/canvas \
middlewares/lvgl/src/widgets/chart \
middlewares/lvgl/src/widgets/checkbox \
middlewares/lvgl/src/widgets/colorwheel \
middlewares/lvgl/src/widgets/dropdown \
middlewares/lvgl/src/widgets/img \
middlewares/lvgl/src/widgets/imgbtn \
middlewares/lvgl/src/widgets/keyboard \
middlewares/lvgl/src/widgets/label \
middlewares/lvgl/src/widgets/led \
middlewares/lvgl/src/widgets/line \
middlewares/lvgl/src/widgets/list \
middlewares/lvgl/src/widgets/menu \
middlewares/lvgl/src/widgets/meter \
middlewares/lvgl/src/widgets/msgbox \
middlewares/lvgl/src/widgets/objx_templ \
middlewares/lvgl/src/widgets/roller \
middlewares/lvgl/src/widgets/slider \
middlewares/lvgl/src/widgets/span \
middlewares/lvgl/src/widgets/spinbox \
middlewares/lvgl/src/widgets/spinner \
middlewares/lvgl/src/widgets/switch \
middlewares/lvgl/src/widgets/table \
middlewares/lvgl/src/widgets/tabview \
middlewares/lvgl/src/widgets/textarea \
middlewares/lvgl/src/widgets/tileview \
middlewares/lvgl/src/widgets/win \
thread \
utils \

