/*
 * thread_cli.c
 *
 *  Created on: Aug 29, 2022
 *      Author: sandeep
 */

/* Dimensions the buffer into which input characters are placed. */
#define cmdMAX_INPUT_SIZE   60

/* Dimensions the buffer into which string outputs can be placed. */
#define cmdMAX_OUTPUT_SIZE  1024


/* Standard includes. */
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

/* Kernel includes. */
#include "FreeRTOS.h"
#include "task.h"

/* FreeRTOS+CLI includes. */
#include "FreeRTOS_CLI.h"

/* Hardware includes. */
#include "inc/hw_memmap.h"
#include "inc/hw_sysctl.h"
#include "driverlib/sysexc.h" //System Exception
#include "driverlib/systick.h" //SysTick
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h" //NIVC
#include "driverlib/pin_map.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/watchdog.h"
#include "driverlib/timer.h"
#include "driverlib/uart.h"
#include "driverlib/udma.h"
#include "driverlib/comp.h" // Comparator
#include "driverlib/adc.h"
#include "driverlib/aes.h"
#include "driverlib/can.h"
#include "driverlib/crc.h"
#include "driverlib/des.h" //Data encryption and decryption
#include "driverlib/eeprom.h"
#include "driverlib/emac.h" //Ethernet
#include "driverlib/epi.h" // external peripheral interface
#include "driverlib/flash.h"
#include "driverlib/fpu.h" //Floating Point Unit
//#include "driverlib/hibernate.h" //RTC
#include "driverlib/i2c.h"
#include "driverlib/lcd.h"
#include "driverlib/mpu.h" // Memory protection unit
#include "driverlib/onewire.h" // 1-Wire master
#include "driverlib/pwm.h"
#include "driverlib/qei.h" // Quadrature Encoder
#include "driverlib/shamd5.h" // SHA MD5
#include "driverlib/ssi.h" // QSPI Microwire etc
//#include "driverlib/sw_crc.h" //Soft CRC

#include "drivers/rtos_hw_drivers.h"

#include "utils/uartstdio.h"

#include "utils/cli_commands.h"

/* The system clock frequency. */
extern uint32_t g_ui32SysClock;

#include "thread_cli.h"

void prvCommandInterpreterTask( void *pvParameters ){

    BaseType_t xMoreDataToFollow;
    static signed char cInputString[ cmdMAX_INPUT_SIZE ], cOutputString[ cmdMAX_OUTPUT_SIZE ];

    for (;;){

        UARTgets((char *)cInputString,cmdMAX_INPUT_SIZE); // This is blocking, use peak for non blocking

        do
        {
            /* Pass the string to FreeRTOS+CLI. */
            xMoreDataToFollow = FreeRTOS_CLIProcessCommand( (char *)cInputString,(char *) cOutputString, cmdMAX_OUTPUT_SIZE );

            /* Send the output generated by the command's implementation. */
            //sendto( xSocket, cOutputString,  strlen( cOutputString ), 0, ( SOCKADDR * ) &xClient, xClientAddressLength );
           UARTprintf((const char *)cOutputString);

        } while( xMoreDataToFollow != pdFALSE ); /* Until the command does not generate any more output. */
    }

}


